In [1]:
# Create Model Class

import torch
import torch.nn as nn

class Model(nn.Module):

    def __init__(self, num_features):

      super().__init__()

      self.linear = nn.Linear(num_features, 1)
      self.sigmoid = nn.Sigmoid()

    def forward(self, features):

      out = self.linear(features)
      out = self.sigmoid(out)

      return out

In [2]:
# Create Dataset
features = torch.rand(10, 5)

# Create Model
model = Model(features.shape[1])

# Call Model for Forward Pass
# model.forward(features)
model(features)

tensor([[0.6282],
        [0.6680],
        [0.6934],
        [0.6890],
        [0.7021],
        [0.7401],
        [0.6828],
        [0.6389],
        [0.6703],
        [0.6942]], grad_fn=<SigmoidBackward0>)

In [3]:
# Show Model Weights

model.linear.weight

Parameter containing:
tensor([[ 0.1985,  0.3937,  0.3225, -0.1638,  0.2458]], requires_grad=True)

In [4]:
model.linear.bias

Parameter containing:
tensor([0.3328], requires_grad=True)

In [5]:
!pip install torchinfo

In [6]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [7]:
# Create Model Class

import torch
import torch.nn as nn

class Model(nn.Module):

    def __init__(self, num_features):

      super().__init__()

      self.linear1 = nn.Linear(num_features, 3)
      self.relu = nn.ReLU()
      self.linear2 = nn.Linear(3, 1)
      self.sigmoid = nn.Sigmoid()

    def forward(self, features):

      out = self.linear1(features)
      out = self.relu(out)
      out = self.linear2(out)
      out = self.sigmoid(out)

      return out

In [8]:
# Create Dataset
features = torch.rand(10, 5)

# Create Model
model = Model(features.shape[1])

# Call Model for Forward Pass
# model.forward(features)
model(features)

tensor([[0.5639],
        [0.6056],
        [0.5734],
        [0.6063],
        [0.5891],
        [0.5809],
        [0.5868],
        [0.5832],
        [0.5787],
        [0.5809]], grad_fn=<SigmoidBackward0>)

In [9]:
# Show Model Weights

model.linear1.weight

Parameter containing:
tensor([[-0.0080, -0.2807, -0.1587, -0.0786,  0.3778],
        [ 0.0295,  0.4462, -0.1078, -0.2629,  0.3296],
        [ 0.1430,  0.1999, -0.0881,  0.3996, -0.3090]], requires_grad=True)

In [10]:
model.linear2.weight

Parameter containing:
tensor([[ 0.4853,  0.2975, -0.4516]], requires_grad=True)

In [11]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [12]:
# Create Model Class

import torch
import torch.nn as nn

class Model(nn.Module):

    def __init__(self, num_features):

      super().__init__()
      self.network = nn.Sequential(
          nn.Linear(num_features, 3),
          nn.ReLU(),
          nn.Linear(3, 1),
          nn.Sigmoid()
      )

    def forward(self, features):

      out = self.network(features)

      return out

In [13]:
# Create Dataset
features = torch.rand(10, 5)

# Create Model
model = Model(features.shape[1])

# Call Model for Forward Pass
# model.forward(features)
model(features)

tensor([[0.5766],
        [0.5696],
        [0.5622],
        [0.5651],
        [0.5766],
        [0.5544],
        [0.5766],
        [0.5633],
        [0.5739],
        [0.5766]], grad_fn=<SigmoidBackward0>)