In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'],inplace=True)

In [5]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

# Train Test Split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

# Scaling

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
X_train

array([[ 3.2159744 ,  1.22645756,  3.33767132, ...,  2.59282612,
        -0.87735935,  1.14822737],
       [-1.39029168,  0.49412398, -1.37292842, ..., -1.36765895,
        -0.84382064,  0.43692568],
       [ 0.00500841,  0.97705603,  0.02317953, ...,  0.93162519,
         2.90612671,  1.01185818],
       ...,
       [-1.32944926, -0.60324275, -1.29325922, ..., -0.52477015,
         0.12401075,  0.7745758 ],
       [-0.32685934, -0.20646759, -0.30477095, ...,  0.15184685,
         0.33322842, -0.04800315],
       [ 0.09525314, -1.95227831,  0.08261528, ...,  0.09571495,
        -0.02451783, -0.21764642]])

In [9]:
y_train

82     M
412    B
214    M
297    M
533    M
      ..
32     M
33     M
341    B
356    B
123    B
Name: diagnosis, Length: 455, dtype: object

# Label Encoding

In [10]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [11]:
y_train

array([1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,

# NumPy arrays to PyTorch Tensors

In [12]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [13]:
X_train_tensor

tensor([[ 3.2160,  1.2265,  3.3377,  ...,  2.5928, -0.8774,  1.1482],
        [-1.3903,  0.4941, -1.3729,  ..., -1.3677, -0.8438,  0.4369],
        [ 0.0050,  0.9771,  0.0232,  ...,  0.9316,  2.9061,  1.0119],
        ...,
        [-1.3294, -0.6032, -1.2933,  ..., -0.5248,  0.1240,  0.7746],
        [-0.3269, -0.2065, -0.3048,  ...,  0.1518,  0.3332, -0.0480],
        [ 0.0953, -1.9523,  0.0826,  ...,  0.0957, -0.0245, -0.2176]])

In [14]:
X_train_tensor.shape

torch.Size([455, 30])

In [15]:
y_train_tensor.shape

torch.Size([455])

# Defining the Model

In [16]:
import torch.nn as nn

class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

# Important Parameters

In [17]:
learning_rate = 0.1
epochs = 25

# Training Pipeline

In [18]:
# CREATE MODEL
model = MySimpleNN(X_train_tensor.shape[1])
model.linear.weight

Parameter containing:
tensor([[-0.1162,  0.1512,  0.1809, -0.0894,  0.1118,  0.1688, -0.0603,  0.0242,
          0.0302,  0.0966, -0.0460, -0.0368, -0.1359,  0.1521, -0.0407,  0.0129,
         -0.1275,  0.0713, -0.0770,  0.1335,  0.0365, -0.0016,  0.1245,  0.0313,
          0.1271, -0.0710,  0.1278,  0.0827, -0.0671, -0.0924]],
       requires_grad=True)

In [19]:
model.linear.bias

Parameter containing:
tensor([-0.1684], requires_grad=True)

In [20]:
# CREATE MODEL
model = MySimpleNN(X_train_tensor.shape[1])

# define loop
for epoch in range(epochs):

  # Forward Pass
  y_pred = model(X_train_tensor)
  # print(y_pred)

  # Calculate Loss
  loss = model.loss_function(y_pred, y_train_tensor)
  # print(f'Epoch: {epoch + 1}, Loss : {loss.item()}')

  # Backward Pass
  loss.backward()

  # Parameters Update
  with torch.no_grad():
    model.linear.weight -= learning_rate * model.linear.weight.grad
    model.linear.bias -= learning_rate * model.linear.bias.grad

  # Zero Gradients
  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()

  # Print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss : {loss.item()}')

Epoch: 1, Loss : 0.8071365356445312
Epoch: 2, Loss : 0.7704284191131592
Epoch: 3, Loss : 0.7458044290542603
Epoch: 4, Loss : 0.7294144630432129
Epoch: 5, Loss : 0.718281090259552
Epoch: 6, Loss : 0.7104092836380005
Epoch: 7, Loss : 0.7045769095420837
Epoch: 8, Loss : 0.7000638246536255
Epoch: 9, Loss : 0.6964460611343384
Epoch: 10, Loss : 0.6934671998023987
Epoch: 11, Loss : 0.6909638047218323
Epoch: 12, Loss : 0.6888271570205688
Epoch: 13, Loss : 0.6869800090789795
Epoch: 14, Loss : 0.685365617275238
Epoch: 15, Loss : 0.6839413046836853
Epoch: 16, Loss : 0.6826738119125366
Epoch: 17, Loss : 0.681536853313446
Epoch: 18, Loss : 0.6805099248886108
Epoch: 19, Loss : 0.6795762181282043
Epoch: 20, Loss : 0.6787226796150208
Epoch: 21, Loss : 0.6779383420944214
Epoch: 22, Loss : 0.6772143840789795
Epoch: 23, Loss : 0.6765435338020325
Epoch: 24, Loss : 0.6759198307991028
Epoch: 25, Loss : 0.6753382682800293


In [21]:
model.linear.weight

Parameter containing:
tensor([[-0.0850,  0.0365,  0.0435,  0.0064,  0.0183,  0.0179,  0.1162, -0.0030,
         -0.0578,  0.0437, -0.0562, -0.0221,  0.0746, -0.0892,  0.0538,  0.0424,
         -0.1709,  0.0644, -0.0065, -0.0637,  0.0970,  0.0008,  0.1004, -0.1043,
         -0.0129,  0.0587, -0.0176, -0.1391,  0.0505, -0.0119]],
       requires_grad=True)

In [22]:
model.linear.bias

Parameter containing:
tensor([-0.2269], requires_grad=True)

# Evaluation

In [23]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)

print(y_pred)

tensor([[0.4314],
        [0.4279],
        [0.4123],
        [0.4389],
        [0.4798],
        [0.4225],
        [0.4627],
        [0.4534],
        [0.4707],
        [0.4457],
        [0.4000],
        [0.4223],
        [0.4055],
        [0.4438],
        [0.4246],
        [0.4336],
        [0.4025],
        [0.4550],
        [0.4331],
        [0.4331],
        [0.4480],
        [0.4381],
        [0.3973],
        [0.4394],
        [0.4336],
        [0.4454],
        [0.4402],
        [0.4459],
        [0.4468],
        [0.4188],
        [0.4227],
        [0.4429],
        [0.2591],
        [0.4575],
        [0.4089],
        [0.4693],
        [0.4257],
        [0.4382],
        [0.4591],
        [0.4213],
        [0.4210],
        [0.4576],
        [0.5140],
        [0.4294],
        [0.4407],
        [0.4253],
        [0.4360],
        [0.4339],
        [0.4394],
        [0.4475],
        [0.4486],
        [0.4476],
        [0.4730],
        [0.4724],
        [0.5048],
        [0

In [24]:
print(y_train_tensor)

tensor([1., 0., 1., 1., 1., 1., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1.,
        0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1.,
        0., 1., 1., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0.,
        0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 1.,
        1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 1.,
        1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0.,
        0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1.,
        0., 1., 0., 0., 1., 0., 1., 1., 1., 0., 1., 0., 0., 0., 1., 0., 0., 1.,
        0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1.,
        0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0.,
        1., 0., 1., 0., 1., 0., 0., 1., 

In [25]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()

print(y_pred)

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
      

In [26]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6495844721794128


In [27]:
import torch.nn as nn

class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [28]:
learning_rate = 0.1
epochs = 25

In [29]:
# Define Loss Function

loss_function = nn.BCELoss()

In [30]:
type(loss_function)

torch.nn.modules.loss.BCELoss

In [31]:
# CREATE MODEL
model = MySimpleNN(X_train_tensor.shape[1])

# define loop
for epoch in range(epochs):

  # Forward Pass
  y_pred = model(X_train_tensor)
  # print(y_pred)

  # Calculate Loss
  loss = loss_function(y_pred, y_train_tensor.view(-1, 1))

  # Backward Pass
  loss.backward()

  # Parameters Update
  with torch.no_grad():
    model.linear.weight -= learning_rate * model.linear.weight.grad
    model.linear.bias -= learning_rate * model.linear.bias.grad

  # Zero Gradients
  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()

  # Print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss : {loss.item()}')

Epoch: 1, Loss : 0.6665010452270508
Epoch: 2, Loss : 0.5355116128921509
Epoch: 3, Loss : 0.4582623243331909
Epoch: 4, Loss : 0.4066227972507477
Epoch: 5, Loss : 0.36916953325271606
Epoch: 6, Loss : 0.34047234058380127
Epoch: 7, Loss : 0.3176073729991913
Epoch: 8, Loss : 0.2988514006137848
Epoch: 9, Loss : 0.2831179201602936
Epoch: 10, Loss : 0.26968443393707275
Epoch: 11, Loss : 0.2580498158931732
Epoch: 12, Loss : 0.24785418808460236
Epoch: 13, Loss : 0.23883146047592163
Epoch: 14, Loss : 0.2307800054550171
Epoch: 15, Loss : 0.22354377806186676
Epoch: 16, Loss : 0.21699988842010498
Epoch: 17, Loss : 0.21104978024959564
Epoch: 18, Loss : 0.20561353862285614
Epoch: 19, Loss : 0.20062534511089325
Epoch: 20, Loss : 0.19603057205677032
Epoch: 21, Loss : 0.191783145070076
Epoch: 22, Loss : 0.18784424662590027
Epoch: 23, Loss : 0.18418055772781372
Epoch: 24, Loss : 0.18076346814632416
Epoch: 25, Loss : 0.177568256855011


In [32]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5443213582038879


In [33]:
import torch.nn as nn

class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [34]:
learning_rate = 0.1
epochs = 25

In [35]:
# Define Loss Function

loss_function = nn.BCELoss()

In [36]:
# CREATE MODEL
model = MySimpleNN(X_train_tensor.shape[1])

# Define Optimizer

optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loop
for epoch in range(epochs):

  # Forward Pass
  y_pred = model(X_train_tensor)
  # print(y_pred)

  # Calculate Loss
  loss = loss_function(y_pred, y_train_tensor.view(-1, 1))

  # Clear gradients
  optimizer.zero_grad()

  # Backward Pass
  loss.backward()

  # Parameters Update
  optimizer.step()

  # Print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss : {loss.item()}')

Epoch: 1, Loss : 0.8429097533226013
Epoch: 2, Loss : 0.6018521189689636
Epoch: 3, Loss : 0.48269355297088623
Epoch: 4, Loss : 0.41420233249664307
Epoch: 5, Loss : 0.3691432476043701
Epoch: 6, Loss : 0.3368622362613678
Epoch: 7, Loss : 0.3123722970485687
Epoch: 8, Loss : 0.2930120825767517
Epoch: 9, Loss : 0.277225136756897
Epoch: 10, Loss : 0.26403772830963135
Epoch: 11, Loss : 0.25280776619911194
Epoch: 12, Loss : 0.24309387803077698
Epoch: 13, Loss : 0.23458196222782135
Epoch: 14, Loss : 0.2270420491695404
Epoch: 15, Loss : 0.22030138969421387
Epoch: 16, Loss : 0.21422763168811798
Epoch: 17, Loss : 0.20871730148792267
Epoch: 18, Loss : 0.20368829369544983
Epoch: 19, Loss : 0.19907444715499878
Epoch: 20, Loss : 0.1948218047618866
Epoch: 21, Loss : 0.19088581204414368
Epoch: 22, Loss : 0.18722927570343018
Epoch: 23, Loss : 0.1838209331035614
Epoch: 24, Loss : 0.1806342601776123
Epoch: 25, Loss : 0.17764651775360107


In [37]:
import torch.nn as nn

class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out