In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'],inplace=True)

In [5]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

# Train Test Split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

# Scaling

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
X_train

array([[ 0.01630569,  0.65668699,  0.16528741, ...,  0.95155294,
        -0.10606567,  1.70783728],
       [-0.66014714, -0.08404668, -0.68476406, ..., -0.67772868,
        -0.60941753, -0.19218143],
       [ 0.87239743, -0.51325685,  0.83931197, ...,  1.05881112,
         0.37285164, -0.12365055],
       ...,
       [-0.09596864,  0.0682537 , -0.14936579, ..., -0.83012469,
        -0.64525488, -0.81010155],
       [-0.67137457, -0.62863593, -0.54329208, ...,  1.0707287 ,
         4.66681772,  1.12532478],
       [ 0.54680188, -1.02553996,  0.48563201, ..., -0.0256883 ,
        -0.21357772, -0.75242139]])

In [9]:
y_train

62     M
211    B
253    M
252    M
465    B
      ..
7      M
19     B
438    B
146    M
406    B
Name: diagnosis, Length: 455, dtype: object

# Label Encoding

In [10]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [11]:
y_train

array([1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,

# NumPy arrays to PyTorch Tensors

In [12]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [13]:
X_train_tensor

tensor([[ 0.0163,  0.6567,  0.1653,  ...,  0.9516, -0.1061,  1.7078],
        [-0.6601, -0.0840, -0.6848,  ..., -0.6777, -0.6094, -0.1922],
        [ 0.8724, -0.5133,  0.8393,  ...,  1.0588,  0.3729, -0.1237],
        ...,
        [-0.0960,  0.0683, -0.1494,  ..., -0.8301, -0.6453, -0.8101],
        [-0.6714, -0.6286, -0.5433,  ...,  1.0707,  4.6668,  1.1253],
        [ 0.5468, -1.0255,  0.4856,  ..., -0.0257, -0.2136, -0.7524]])

In [14]:
X_train_tensor.shape

torch.Size([455, 30])

In [15]:
y_train_tensor.shape

torch.Size([455])

# Defining the Model

In [16]:
import torch.nn as nn

class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

# Important Parameters

In [17]:
learning_rate = 0.1
epochs = 25

# Training Pipeline

In [18]:
# CREATE MODEL
model = MySimpleNN(X_train_tensor.shape[1])
model.linear.weight

Parameter containing:
tensor([[ 0.1116, -0.0659, -0.0577, -0.0453,  0.0948, -0.1468, -0.1731, -0.0785,
         -0.1361, -0.0760, -0.1213,  0.0740, -0.0633, -0.0155,  0.1786, -0.0925,
         -0.0193,  0.0477,  0.0817,  0.1259, -0.1320,  0.1652,  0.0025,  0.0427,
          0.1155,  0.1086, -0.0563,  0.0245, -0.0317,  0.1214]],
       requires_grad=True)

In [19]:
model.linear.bias

Parameter containing:
tensor([-0.1099], requires_grad=True)

In [20]:
# CREATE MODEL
model = MySimpleNN(X_train_tensor.shape[1])

# define loop
for epoch in range(epochs):

  # Forward Pass
  y_pred = model(X_train_tensor)
  # print(y_pred)

  # Calculate Loss
  loss = model.loss_function(y_pred, y_train_tensor)
  # print(f'Epoch: {epoch + 1}, Loss : {loss.item()}')

  # Backward Pass
  loss.backward()

  # Parameters Update
  with torch.no_grad():
    model.linear.weight -= learning_rate * model.linear.weight.grad
    model.linear.bias -= learning_rate * model.linear.bias.grad

  # Zero Gradients
  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()

  # Print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss : {loss.item()}')

Epoch: 1, Loss : 0.7154801487922668
Epoch: 2, Loss : 0.7086636424064636
Epoch: 3, Loss : 0.703091025352478
Epoch: 4, Loss : 0.6985188722610474
Epoch: 5, Loss : 0.69474858045578
Epoch: 6, Loss : 0.6916191577911377
Epoch: 7, Loss : 0.68900066614151
Epoch: 8, Loss : 0.6867896318435669
Epoch: 9, Loss : 0.6849039196968079
Epoch: 10, Loss : 0.6832785606384277
Epoch: 11, Loss : 0.6818628311157227
Epoch: 12, Loss : 0.6806171536445618
Epoch: 13, Loss : 0.6795104146003723
Epoch: 14, Loss : 0.6785182356834412
Epoch: 15, Loss : 0.6776217222213745
Epoch: 16, Loss : 0.676805853843689
Epoch: 17, Loss : 0.6760589480400085
Epoch: 18, Loss : 0.6753714084625244
Epoch: 19, Loss : 0.6747356057167053
Epoch: 20, Loss : 0.6741454601287842
Epoch: 21, Loss : 0.6735959053039551
Epoch: 22, Loss : 0.673082709312439
Epoch: 23, Loss : 0.6726023554801941
Epoch: 24, Loss : 0.6721517443656921
Epoch: 25, Loss : 0.6717285513877869


In [21]:
model.linear.weight

Parameter containing:
tensor([[-0.0562,  0.0407, -0.2096, -0.0019,  0.0019,  0.1272,  0.0553,  0.1219,
         -0.0782, -0.0460,  0.0328,  0.0440, -0.0933, -0.0377, -0.0042,  0.1265,
          0.0647,  0.0280, -0.0520, -0.1356,  0.0784, -0.0232,  0.0805,  0.0724,
         -0.0555,  0.0493, -0.1409, -0.1373,  0.0331,  0.0088]],
       requires_grad=True)

In [22]:
model.linear.bias

Parameter containing:
tensor([-0.2711], requires_grad=True)

# Evaluation

In [23]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)

print(y_pred)

tensor([[0.5097],
        [0.4273],
        [0.4017],
        [0.3946],
        [0.4649],
        [0.3895],
        [0.4328],
        [0.4226],
        [0.3578],
        [0.4053],
        [0.4062],
        [0.4050],
        [0.3910],
        [0.3848],
        [0.4313],
        [0.4537],
        [0.4432],
        [0.4516],
        [0.4416],
        [0.4119],
        [0.4899],
        [0.4444],
        [0.4572],
        [0.4260],
        [0.4791],
        [0.4011],
        [0.4157],
        [0.4051],
        [0.3462],
        [0.4285],
        [0.4771],
        [0.4433],
        [0.4248],
        [0.4339],
        [0.4658],
        [0.4122],
        [0.5017],
        [0.4144],
        [0.4491],
        [0.4489],
        [0.4565],
        [0.4117],
        [0.5474],
        [0.4037],
        [0.4077],
        [0.4321],
        [0.4436],
        [0.4509],
        [0.4406],
        [0.4349],
        [0.4211],
        [0.4446],
        [0.4335],
        [0.3941],
        [0.4220],
        [0

In [24]:
print(y_train_tensor)

tensor([1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 1., 0., 1., 0.,
        0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        1., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 1., 0.,
        0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 1., 0.,
        0., 1., 0., 1., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
        0., 0., 0., 1., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0.,
        1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1.,
        1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 1., 0., 1., 1.,
        0., 0., 1., 0., 1., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 1., 1., 0., 0., 

In [25]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()

print(y_pred)

tensor([[1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
      

In [26]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6281933188438416


In [27]:
import torch.nn as nn

class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [28]:
learning_rate = 0.1
epochs = 25

In [29]:
# Define Loss Function

loss_function = nn.BCELoss()

In [30]:
type(loss_function)

torch.nn.modules.loss.BCELoss

In [31]:
# CREATE MODEL
model = MySimpleNN(X_train_tensor.shape[1])

# define loop
for epoch in range(epochs):

  # Forward Pass
  y_pred = model(X_train_tensor)
  # print(y_pred)

  # Calculate Loss
  loss = loss_function(y_pred, y_train_tensor.view(-1, 1))

  # Backward Pass
  loss.backward()

  # Parameters Update
  with torch.no_grad():
    model.linear.weight -= learning_rate * model.linear.weight.grad
    model.linear.bias -= learning_rate * model.linear.bias.grad

  # Zero Gradients
  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()

  # Print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss : {loss.item()}')

Epoch: 1, Loss : 0.7886497974395752
Epoch: 2, Loss : 0.5799980163574219
Epoch: 3, Loss : 0.47570210695266724
Epoch: 4, Loss : 0.4137343764305115
Epoch: 5, Loss : 0.371707558631897
Epoch: 6, Loss : 0.3408229351043701
Epoch: 7, Loss : 0.3168836236000061
Epoch: 8, Loss : 0.29761040210723877
Epoch: 9, Loss : 0.2816482484340668
Epoch: 10, Loss : 0.26813578605651855
Epoch: 11, Loss : 0.2564966082572937
Epoch: 12, Loss : 0.24632863700389862
Epoch: 13, Loss : 0.23734205961227417
Epoch: 14, Loss : 0.22932210564613342
Epoch: 15, Loss : 0.2221057265996933
Epoch: 16, Loss : 0.21556682884693146
Epoch: 17, Loss : 0.20960596203804016
Epoch: 18, Loss : 0.20414361357688904
Epoch: 19, Loss : 0.19911524653434753
Epoch: 20, Loss : 0.19446782767772675
Epoch: 21, Loss : 0.19015730917453766
Epoch: 22, Loss : 0.1861465722322464
Epoch: 23, Loss : 0.18240423500537872
Epoch: 24, Loss : 0.17890331149101257
Epoch: 25, Loss : 0.17562060058116913


In [32]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5418590307235718


In [33]:
import torch.nn as nn

class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [34]:
learning_rate = 0.1
epochs = 25

In [35]:
# Define Loss Function

loss_function = nn.BCELoss()

In [36]:
# CREATE MODEL
model = MySimpleNN(X_train_tensor.shape[1])

# Define Optimizer

optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loop
for epoch in range(epochs):

  # Forward Pass
  y_pred = model(X_train_tensor)
  # print(y_pred)

  # Calculate Loss
  loss = loss_function(y_pred, y_train_tensor.view(-1, 1))

  # Clear gradients
  optimizer.zero_grad()

  # Backward Pass
  loss.backward()

  # Parameters Update
  optimizer.step()

  # Print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss : {loss.item()}')

Epoch: 1, Loss : 0.7186486124992371
Epoch: 2, Loss : 0.5380750298500061
Epoch: 3, Loss : 0.44595202803611755
Epoch: 4, Loss : 0.3895570635795593
Epoch: 5, Loss : 0.35079529881477356
Epoch: 6, Loss : 0.3221350908279419
Epoch: 7, Loss : 0.2998594045639038
Epoch: 8, Loss : 0.2819085717201233
Epoch: 9, Loss : 0.26704269647598267
Epoch: 10, Loss : 0.2544669806957245
Epoch: 11, Loss : 0.24364648759365082
Epoch: 12, Loss : 0.2342066764831543
Epoch: 13, Loss : 0.22587667405605316
Epoch: 14, Loss : 0.21845494210720062
Epoch: 15, Loss : 0.21178825199604034
Epoch: 16, Loss : 0.20575763285160065
Epoch: 17, Loss : 0.20026898384094238
Epoch: 18, Loss : 0.1952468752861023
Epoch: 19, Loss : 0.19062981009483337
Epoch: 20, Loss : 0.18636728823184967
Epoch: 21, Loss : 0.18241716921329498
Epoch: 22, Loss : 0.17874398827552795
Epoch: 23, Loss : 0.17531771957874298
Epoch: 24, Loss : 0.17211276292800903
Epoch: 25, Loss : 0.16910691559314728


In [37]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5366266369819641
