In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'],inplace=True)

In [5]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

# Train Test Split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

# Scaling

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
X_train

array([[-0.81610608, -1.48649952, -0.77741961, ...,  0.27552056,
         0.74126832,  0.46834202],
       [-1.82993511,  1.37930487, -1.82199331, ..., -1.74291781,
         0.27200007,  0.86418222],
       [-0.4009544 , -1.29895286, -0.41982528, ..., -0.7715252 ,
        -0.8624765 , -0.7870682 ],
       ...,
       [-0.21198881,  2.57548659, -0.23065705, ..., -0.55406067,
        -1.14733055, -0.37480309],
       [ 0.08577515, -0.66769827,  0.09333503, ...,  0.42253883,
         0.26376729,  0.22142095],
       [ 0.16880549,  0.48731468,  0.15141299, ...,  1.06574377,
         1.32579543,  1.41277404]])

In [9]:
y_train

380    B
538    B
294    B
46     B
272    M
      ..
349    B
198    M
455    B
340    B
57     M
Name: diagnosis, Length: 455, dtype: object

# Label Encoding

In [10]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [11]:
y_train

array([0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,

# NumPy arrays to PyTorch Tensors

In [12]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [13]:
X_train_tensor

tensor([[-0.8161, -1.4865, -0.7774,  ...,  0.2755,  0.7413,  0.4683],
        [-1.8299,  1.3793, -1.8220,  ..., -1.7429,  0.2720,  0.8642],
        [-0.4010, -1.2990, -0.4198,  ..., -0.7715, -0.8625, -0.7871],
        ...,
        [-0.2120,  2.5755, -0.2307,  ..., -0.5541, -1.1473, -0.3748],
        [ 0.0858, -0.6677,  0.0933,  ...,  0.4225,  0.2638,  0.2214],
        [ 0.1688,  0.4873,  0.1514,  ...,  1.0657,  1.3258,  1.4128]],
       dtype=torch.float64)

In [14]:
X_train_tensor.shape

torch.Size([455, 30])

In [15]:
y_train_tensor.shape

torch.Size([455])

# Defining the Model

In [16]:
class MySimpleNN():

  def __init__(self, X):
    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss





# Important Parameters

In [17]:
learning_rate = 0.1
epochs = 25

# Training Pipeline

In [18]:
# CREATE MODEL
model = MySimpleNN(X_train_tensor)
model.weights

tensor([[0.3867],
        [0.8036],
        [0.7476],
        [0.1921],
        [0.3106],
        [0.5045],
        [0.0959],
        [0.3735],
        [0.5512],
        [0.2963],
        [0.3392],
        [0.1683],
        [0.6323],
        [0.6119],
        [0.4423],
        [0.5423],
        [0.9565],
        [0.0958],
        [0.1889],
        [0.3585],
        [0.4960],
        [0.2311],
        [0.4763],
        [0.5372],
        [0.8002],
        [0.4040],
        [0.2417],
        [0.2500],
        [0.9163],
        [0.4631]], dtype=torch.float64, requires_grad=True)

In [19]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

In [20]:
# CREATE MODEL
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):

  # Forward Pass
  y_pred = model.forward(X_train_tensor)
  # print(y_pred)

  # Calculate Loss
  loss = model.loss_function(y_pred, y_train_tensor)
  # print(f'Epoch: {epoch + 1}, Loss : {loss.item()}')

  # Backward Pass
  loss.backward()

  # Parameters Update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # Zero Gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # Print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss : {loss.item()}')

Epoch: 1, Loss : 3.7617942706132848
Epoch: 2, Loss : 3.6459338707153597
Epoch: 3, Loss : 3.5288588812722836
Epoch: 4, Loss : 3.4083893469550572
Epoch: 5, Loss : 3.2774343043442378
Epoch: 6, Loss : 3.141942613761036
Epoch: 7, Loss : 3.0040229288714895
Epoch: 8, Loss : 2.8614040669762644
Epoch: 9, Loss : 2.714152022452315
Epoch: 10, Loss : 2.5601804327670985
Epoch: 11, Loss : 2.40678419890396
Epoch: 12, Loss : 2.2511635070471097
Epoch: 13, Loss : 2.0962701655708496
Epoch: 14, Loss : 1.945190904080529
Epoch: 15, Loss : 1.7959820689124308
Epoch: 16, Loss : 1.6519497691424991
Epoch: 17, Loss : 1.5178531570947817
Epoch: 18, Loss : 1.3896473353325107
Epoch: 19, Loss : 1.268008020400383
Epoch: 20, Loss : 1.1610481738010032
Epoch: 21, Loss : 1.0713676763737836
Epoch: 22, Loss : 0.998536222052976
Epoch: 23, Loss : 0.9410351744581656
Epoch: 24, Loss : 0.8965961856362787
Epoch: 25, Loss : 0.8626539351142126


In [21]:
model.weights

tensor([[-0.1115],
        [ 0.4023],
        [-0.2653],
        [ 0.1835],
        [ 0.0139],
        [ 0.1016],
        [-0.5185],
        [ 0.0342],
        [-0.1508],
        [ 0.1110],
        [-0.0746],
        [ 0.2004],
        [ 0.4258],
        [ 0.2651],
        [ 0.0084],
        [ 0.3554],
        [ 0.2941],
        [-0.0396],
        [ 0.7141],
        [-0.1413],
        [ 0.3127],
        [-0.1488],
        [ 0.2836],
        [-0.1966],
        [ 0.4007],
        [-0.0043],
        [-0.4148],
        [ 0.1717],
        [-0.1279],
        [-0.1261]], dtype=torch.float64, requires_grad=True)

In [22]:
model.bias

tensor([-0.0935], dtype=torch.float64, requires_grad=True)

# Evaluation

In [23]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)

print(y_pred)

tensor([[0.6429],
        [0.2752],
        [0.8727],
        [0.5511],
        [0.3927],
        [0.3159],
        [0.8928],
        [0.2361],
        [0.5015],
        [0.8267],
        [0.2957],
        [0.7720],
        [0.2187],
        [0.6187],
        [0.1926],
        [0.3321],
        [0.1728],
        [0.6890],
        [0.3299],
        [0.1963],
        [0.1871],
        [0.1382],
        [0.5606],
        [0.3013],
        [0.7548],
        [0.2025],
        [0.5298],
        [0.3065],
        [0.1403],
        [0.2855],
        [0.1711],
        [0.4460],
        [0.3638],
        [0.8660],
        [0.2399],
        [0.6177],
        [0.8362],
        [0.3363],
        [0.1719],
        [0.2108],
        [0.9130],
        [0.1943],
        [0.5636],
        [0.6695],
        [0.3068],
        [0.3282],
        [0.7935],
        [0.2117],
        [0.9649],
        [0.1862],
        [0.1482],
        [0.1543],
        [0.2790],
        [0.6275],
        [0.3293],
        [0

In [24]:
print(y_train_tensor)

tensor([0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
        0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
        1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
        0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
        0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1,
        1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,
        1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
        1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
        0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
        1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,
        0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,

In [25]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()

print(y_pred)

tensor([[1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
      

In [26]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5196983814239502
