In [1]:
import torch
print(torch.__version__)

2.8.0+cu126


In [2]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


# Creating a Tensor

In [3]:
# using empty
torch.empty(2, 3)


tensor([[ 0.0000e+00,  0.0000e+00,  5.8434e-43],
        [ 0.0000e+00, -1.1776e+07,  4.3628e-41]])

In [4]:
a = torch.empty(2, 3)

In [5]:
# check type
type(a)

torch.Tensor

In [6]:
# using zeros
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# using ones
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# using rand
torch.rand(2, 3)

tensor([[0.5254, 0.7387, 0.8206],
        [0.3567, 0.6022, 0.6926]])

In [9]:
# use of seed
torch.rand(2, 3)

tensor([[0.5269, 0.2980, 0.6306],
        [0.5731, 0.1663, 0.9163]])

In [10]:
# manual seed
torch.manual_seed(100)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
torch.manual_seed(100)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
# other ways

# arange
print("using arang ->", torch.arange(0,10))
print("using arang ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3,3), 5))

using arang -> tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
using arang -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# Tensor Shapes

In [14]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
x.shape

torch.Size([2, 3])

In [16]:
torch.empty_like(x)

tensor([[    84792,         0,         0],
        [      113, 347292688, 347319824]])

In [17]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [18]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [19]:
# torch.rand_like(x)
# NotImplementedError                       Traceback (most recent call last)
# /tmp/ipython-input-1888830451.py in <cell line: 0>()
# ----> 1 torch.rand_like(x)
#       2
#       3 # reason :- rand generates floats in between 0 to 1, therefore we need to tell explicitly to genrate float

# NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

# reason :- rand generates floats in between 0 to 1, therefore we need to tell explicitly to genrate float

In [20]:
torch.rand_like(x, dtype = torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# Tensor Data Types

In [21]:
# find data type
x.dtype

torch.int64

In [22]:
# assign data type
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [23]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [24]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


# Mathematical OPerations

## 1. Scalar Operation

In [25]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [26]:
# addition
x + 2

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])

In [27]:
# subtraction
x - 2

tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])

In [28]:
# multiplication
x * 3

tensor([[2.1353, 2.3627],
        [1.2549, 2.7042]])

In [29]:
# division
x / 3

tensor([[0.2373, 0.2625],
        [0.1394, 0.3005]])

In [30]:
# int division
(x * 100)//3

tensor([[23., 26.],
        [13., 30.]])

In [31]:
# mod
((x * 100)//3)%2

tensor([[1., 0.],
        [1., 0.]])

In [32]:
# power
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

## 2. Element wise operation

In [33]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [34]:
# add
a + b

tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])

In [35]:
# sub
a - b

tensor([[ 0.4411, -0.2205, -0.2201],
        [-0.6455, -0.5661,  0.3346]])

In [36]:
# multiply
a * b

tensor([[0.5540, 0.7391, 0.0994],
        [0.2866, 0.1328, 0.4030]])

In [37]:
# division
a / b

tensor([[1.7938, 0.7743, 0.5042],
        [0.3190, 0.2397, 1.6841]])

In [38]:
# power
a ** b

tensor([[0.9983, 0.7614, 0.5145],
        [0.3218, 0.2771, 0.9096]])

In [39]:
# mod
a % b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [40]:
c = torch.tensor([1, -2, 3, -4])

In [41]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [42]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [43]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [44]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [45]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [46]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [47]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

## 3. Reduction Operation

In [48]:
e = torch.randint(size = (2,3), low = 0, high = 10)
e

tensor([[8, 0, 7],
        [0, 0, 9]])

In [49]:
e = torch.randint(size = (2,3), low = 0, high = 10, dtype = torch.float32)
e

tensor([[5., 7., 3.],
        [9., 4., 0.]])

In [50]:
# sum
torch.sum(e)

tensor(28.)

In [51]:
# sum along columns
torch.sum(e, dim = 0)

tensor([14., 11.,  3.])

In [52]:
# sum along rows
torch.sum(e, dim = 1)

tensor([15., 13.])

In [53]:
# mean
torch.mean(e)

tensor(4.6667)

In [54]:
# mean along col
torch.mean(e, dim = 0)

tensor([7.0000, 5.5000, 1.5000])

In [55]:
# median
torch.median(e)

tensor(4.)

In [56]:
# max
torch.max(e)

tensor(9.)

In [57]:
# min
torch.min(e)

tensor(0.)

In [58]:
# product
torch.prod(e)

tensor(0.)

In [59]:
# standard deviation
torch.std(e)

tensor(3.1411)

In [60]:
# argmax
torch.argmax(e)

# position of largest element/item

tensor(3)

In [61]:
# argmin
torch.argmin(e)

# position of smallest element/item

tensor(5)

## 4. Matrix Operations

In [62]:
f = torch.randint(size = (2,3), low = 0, high = 10)
g = torch.randint(size = (3,2), low = 0, high = 10)

print(f)
print(g)

tensor([[5, 7, 5],
        [9, 9, 7]])
tensor([[5, 9],
        [8, 9],
        [7, 9]])


In [63]:
# matrix multiplication
torch.matmul(f, g)

tensor([[116, 153],
        [166, 225]])

In [64]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)


tensor(11)

In [65]:
f

tensor([[5, 7, 5],
        [9, 9, 7]])

In [66]:
# transpose
torch.transpose(f, 0, 1)

tensor([[5, 9],
        [7, 9],
        [5, 7]])

In [67]:
h = torch.randint(size = (3,3), low = 0, high = 10, dtype=torch.float32)
h

tensor([[2., 6., 7.],
        [7., 8., 3.],
        [6., 1., 5.]])

In [68]:
# determinanat
torch.det(h)

tensor(-315.)

In [69]:
# inverse
torch.inverse(h)

tensor([[-0.1175,  0.0730,  0.1206],
        [ 0.0540,  0.1016, -0.1365],
        [ 0.1302, -0.1079,  0.0825]])

## 5. Comparison Operations

In [70]:
i = torch.randint(size = (2, 3), low = 0, high = 10)
j = torch.randint(size = (2, 3), low = 0, high = 10)

print(i)
print(j)

tensor([[5, 0, 4],
        [3, 8, 8]])
tensor([[3, 3, 5],
        [0, 6, 4]])


In [71]:
# greater than
i > j

tensor([[ True, False, False],
        [ True,  True,  True]])

In [72]:
# less than
i < j

tensor([[False,  True,  True],
        [False, False, False]])

In [73]:
# equal to
i == j

tensor([[False, False, False],
        [False, False, False]])

In [74]:
# not equal to
i != j

tensor([[True, True, True],
        [True, True, True]])

In [75]:
# greater than equal to
i >= j

tensor([[ True, False, False],
        [ True,  True,  True]])

In [76]:
# less than equal to
i <= j

tensor([[False,  True,  True],
        [False, False, False]])

## 6. Special Functions

In [77]:
k = torch.randint(size = (2, 3), low = 0, high = 10)
k

tensor([[0, 8, 4],
        [7, 2, 3]])

In [78]:
k = torch.randint(size = (2, 3), low = 0, high = 10, dtype=torch.float32)
k

tensor([[8., 5., 6.],
        [2., 9., 5.]])

In [79]:
# log
torch.log(k)

tensor([[2.0794, 1.6094, 1.7918],
        [0.6931, 2.1972, 1.6094]])

In [80]:
# exp
torch.exp(k)

tensor([[2.9810e+03, 1.4841e+02, 4.0343e+02],
        [7.3891e+00, 8.1031e+03, 1.4841e+02]])

In [81]:
# sqrt
torch.sqrt(k)

tensor([[2.8284, 2.2361, 2.4495],
        [1.4142, 3.0000, 2.2361]])

In [82]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9997, 0.9933, 0.9975],
        [0.8808, 0.9999, 0.9933]])

In [83]:
# softmax
torch.softmax(k, dim = 0)

tensor([[0.9975, 0.0180, 0.7311],
        [0.0025, 0.9820, 0.2689]])

In [84]:
# relu
torch.relu(k)

tensor([[8., 5., 6.],
        [2., 9., 5.]])

# Inplace Operations

In [85]:
m = torch.rand(2, 3)
n = torch.rand(2, 3)

print(m)
print(n)

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])
tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])


In [86]:
m + n

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

In [87]:
m.add_(n)

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

In [88]:
m

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

In [89]:
n

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [90]:
torch.relu(m)

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

In [91]:
m.relu_()

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

In [92]:
m

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

In [93]:
# _ resembles inplace operations

# Copying a Tensor

In [94]:
a = torch.rand(2, 3)
a

tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [95]:
b = a

In [96]:
b

tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [97]:
a[0][0] = 0

In [98]:
a

tensor([[0.0000, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [99]:
b

tensor([[0.0000, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [100]:
id(a)

133718516147024

In [101]:
id(b)

133718516147024

In [102]:
b = a.clone()

In [103]:
a

tensor([[0.0000, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [104]:
b

tensor([[0.0000, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [105]:
a[0][0] = 10

In [106]:
a

tensor([[10.0000,  0.2131,  0.3957],
        [ 0.6017,  0.4234,  0.5224]])

In [107]:
b

tensor([[0.0000, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [108]:
id(a)

133718516147024

In [109]:
id(b)

133718516377600

# Tensor Operations on GPU

In [110]:
torch.cuda.is_available()

True

In [111]:
device = torch.device('cuda')

In [112]:
# creating a new tensor on GPU

torch.rand((2, 3), device = device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [113]:
# moving an existing tensor to GPU

a = torch.rand((2, 3))
a

tensor([[0.4175, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [114]:
b = a.to(device)

In [115]:
b + 5

tensor([[5.4175, 5.0340, 5.9157],
        [5.3079, 5.6269, 5.8277]], device='cuda:0')

In [116]:
import torch
import time

# Derfine the size of the matrices
size = 10000 # Large size for performance comparison

# Create random matrices on GPU
matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

# Measure time on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2) # Matrix Multiplication on CPU
cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time:.4f} seconds")

# Move matrices to GPU
matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

# Measure time on GPU
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2) # Matrix Multiplication on GPU
torch.cuda.synchronize()  # Ensure all GPU operations are complete
gpu_time = time.time() - start_time

print(f"Time on GPU: {gpu_time:.4f} seconds")

# Compare results
print("\nSpeedup (CPU time / GPU time):", cpu_time / gpu_time)

Time on CPU: 17.1347 seconds
Time on GPU: 0.5773 seconds

Speedup (CPU time / GPU time): 29.681479147272928


# Reshaping Tensors

In [117]:
a = torch.ones(4, 4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [118]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [119]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [120]:
b = torch.rand(2, 3, 4)
b

tensor([[[0.1174, 0.6532, 0.5115, 0.3094],
         [0.7907, 0.7351, 0.2693, 0.8009],
         [0.5839, 0.0061, 0.4671, 0.8243]],

        [[0.2861, 0.7459, 0.8487, 0.4059],
         [0.2883, 0.2220, 0.6423, 0.7098],
         [0.5644, 0.4549, 0.0729, 0.8535]]])

In [121]:
# permute
b.permute(2, 0, 1)

tensor([[[0.1174, 0.7907, 0.5839],
         [0.2861, 0.2883, 0.5644]],

        [[0.6532, 0.7351, 0.0061],
         [0.7459, 0.2220, 0.4549]],

        [[0.5115, 0.2693, 0.4671],
         [0.8487, 0.6423, 0.0729]],

        [[0.3094, 0.8009, 0.8243],
         [0.4059, 0.7098, 0.8535]]])

In [122]:
b.permute(2, 0, 1).shape

torch.Size([4, 2, 3])

In [123]:
b.permute(2, 1, 0)

tensor([[[0.1174, 0.2861],
         [0.7907, 0.2883],
         [0.5839, 0.5644]],

        [[0.6532, 0.7459],
         [0.7351, 0.2220],
         [0.0061, 0.4549]],

        [[0.5115, 0.8487],
         [0.2693, 0.6423],
         [0.4671, 0.0729]],

        [[0.3094, 0.4059],
         [0.8009, 0.7098],
         [0.8243, 0.8535]]])

In [124]:
b.permute(2, 1, 0).shape

torch.Size([4, 3, 2])

In [125]:
# unsqueeze
# image size
# 226, 226, 3, typical image size
c = torch.rand(226, 226, 3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [126]:
c.unsqueeze(1).shape

torch.Size([226, 1, 226, 3])

In [127]:
c.unsqueeze(2).shape

torch.Size([226, 226, 1, 3])

In [128]:
c.unsqueeze(3).shape

torch.Size([226, 226, 3, 1])

In [129]:
#  squeeze
d = torch.rand(1, 20)
d

tensor([[0.3753, 0.2057, 0.5643, 0.4419, 0.5215, 0.6743, 0.0401, 0.7158, 0.0702,
         0.4443, 0.6302, 0.6179, 0.1797, 0.3512, 0.0083, 0.1996, 0.9616, 0.6520,
         0.2396, 0.8719]])

In [130]:
d.squeeze(0).shape

torch.Size([20])

# NumPy and PyTorch

In [131]:
import numpy as np

In [132]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [133]:
b = a.numpy()

In [134]:
b

array([1, 2, 3])

In [135]:
type(b)

numpy.ndarray

In [136]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [137]:
torch.from_numpy(c)

tensor([1, 2, 3])

In [138]:
d = torch.from_numpy(c)

In [139]:
type(d)

torch.Tensor